// Writes apps/web/src/glue/ao/icons.gen.ts from the design canvas's icon
// component (docs/design/adventurer-olympics/AO-Icon.dc.html), so the table
// draws exactly the drawings the canvas draws and the two cannot drift.
//
//   node scripts/ao-icons.mjs
//
// The component's script is run in a sandbox with a stand-in for the canvas
// runtime's base class; each icon is rendered once, with a sentinel colour
// where the canvas takes its `tint` prop (a coin's colour, the base under an
// adventurer), so the table can put the player's colour there.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { runInNewContext } from 'node:vm';

const html = readFileSync('docs/design/adventurer-olympics/AO-Icon.dc.html', 'utf8');
const script = /<script type="text\/x-dc" data-dc-script data-props='([^']*)'>([\s\S]*?)<\/script>/.exec(html);
if (!script) throw new Error('no component script in AO-Icon.dc.html');
const props = JSON.parse(script[1]);
const names = props.icon.options;
const TINT = '#TINT00';

class DCLogic { constructor(p) { this.props = p ?? {}; this.state = {}; } }
const sandbox = { DCLogic };
runInNewContext(`${script[2]}\n;globalThis.__Component = Component;`, Object.assign(sandbox, { globalThis: sandbox }));
const Component = sandbox.__Component;

const icons = {};
for (const icon of names) {
  const vals = new Component({ icon, size: 100, tint: TINT, flat: true, shadow: false }).renderVals();
  icons[icon] = vals.shapes.map((s) => {
    const out = { d: s.d, f: s.f, w: s.w, s: s.s };
    if (s.o !== 1) out.o = s.o;
    if (s.t && s.t !== 'translate(0 0)') out.t = s.t;
    return out;
  });
}

const lines = [
  '// GENERATED by scripts/ao-icons.mjs from docs/design/adventurer-olympics/AO-Icon.dc.html.',
  '// Do not edit by hand: change the canvas component and run the script.',
  '//',
  '// Each drawing is a list of paths in a 100x100 box: d = path, f = fill,',
  '// w = stroke width, s = stroke colour, o = opacity, t = transform.',
  `// ${JSON.stringify(TINT)} marks where the canvas takes its tint (a player's colour).`,
  '',
  'export interface IconShape { d: string; f: string; w: number; s: string; o?: number; t?: string }',
  '',
  `export const TINT = ${JSON.stringify(TINT)};`,
  '',
  'export const ICONS: Record<string, readonly IconShape[]> = {',
  ...Object.entries(icons).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  '};',
  '',
];
mkdirSync('apps/web/src/glue/ao', { recursive: true });
writeFileSync('apps/web/src/glue/ao/icons.gen.ts', lines.join('\n'));
console.log(`${Object.keys(icons).length} drawings`);
