// Writes apps/web/src/glue/ngg/icons.gen.ts from the design canvas's icon
// registry (docs/design/neither-guts-nor-gears/icons.js), so the table draws
// exactly the marks the canvas draws and the two cannot drift.
//
//   node scripts/ngg-icons.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';

const src = readFileSync('docs/design/neither-guts-nor-gears/icons.js', 'utf8');
const sandbox = { globalThis: {} };
sandbox.globalThis = sandbox;
runInNewContext(src, sandbox);
const { paths } = sandbox.NGG;
// The alias table is private to the registry; read it back through icon().
const aliasMatch = /var ALIAS\s*=\s*(\{[\s\S]*?\});/.exec(src);
const aliases = aliasMatch ? runInNewContext(`(${aliasMatch[1]})`) : {};

const lines = [
  '// GENERATED by scripts/ngg-icons.mjs from docs/design/neither-guts-nor-gears/icons.js.',
  '// Do not edit by hand: change the registry and run the script.',
  '//',
  '// Each mark is up to four solid paths and one dashed path on a 24x24 grid.',
  '',
  'export const ICON_PATHS: Record<string, readonly string[]> = {',
  ...Object.entries(paths).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  '};',
  '',
  'export const ICON_ALIASES: Record<string, string> = {',
  ...Object.entries(aliases).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  '};',
  '',
];
writeFileSync('apps/web/src/glue/ngg/icons.gen.ts', lines.join('\n'));
console.log(`${Object.keys(paths).length} marks, ${Object.keys(aliases).length} aliases`);
